---
- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "51.89.64.134"
    vcenter_user: "root"
    vcenter_pass: "tENHWEmy*gx9NzNTchmL"
  tasks:
  - name: Create a VM in ESXi hostname
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      folder: /ha-datacenter/VM datastore/VM
      name: Test_001
      state: poweredon 
      guest_id: windows9_64Guest
      esxi_hostname: 51.89.64.134
      disk:
      - size_gb: 100
        type: thin
        datastore: VM datastore
      hardware:
        memory_mb: 4096
        num_cpus: 2
        scsi: paravirtual
      networks:
      - name: LAN
        mac: aa:bb:dd:aa:00:14
        ip: 192.168.1.96
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy_vm
